# version: '3.8'
name: api_biblioteca

services:
  api:
    build: ./api/
    ports:
      - '8088:8088'
    command: sh -c "sleep 10s ; go run ./main.go"
    depends_on:
      - db
  
  
  db:
    # image: postgres:latest
    build: ./db/
    restart: always
    environment:
      POSTGRES_PASSWORD: pr-apibiblio
      POSTGRES_USER: postgres
      POSTGRES_DB: biblioteca
    ports:
      - '5432:5432'
    # volumes:
    #  - ./scripts:/docker-entrypoint-initdb.d/