version: '3.8'

services:
  api:
    build: .
    ports:
      - '8080:8088'
    depends_on:
      - db
  
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: biblioteca
    ports:
      - '5345:5345'
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql